# Generated by Django 5.0.7 on 2024-11-15 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("id_number", models.CharField(max_length=20, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("medical_history", models.TextField(blank=True, null=True)),
                ("last_health_check_date", models.DateField(blank=True, null=True)),
                ("health_check_result", models.TextField(blank=True, null=True)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                ("donation_count", models.IntegerField(default=0)),
                ("donation_history", models.TextField(blank=True, null=True)),
                (
                    "registration_status",
                    models.CharField(default="Đã đăng ký", max_length=50),
                ),
                ("willingness_to_participate", models.BooleanField(default=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Người Hiến Máu",
                "verbose_name_plural": "Danh Sách Người Hiến Máu",
            },
        ),
    ]
