# Generated by Django 5.0.7 on 2024-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("registered", "Đã đăng ký"),
                    ("not_registered", "Chưa đăng ký"),
                    ("cancelled", "Đã hủy"),
                    ("donated", "Đã hiến"),
                ],
                default="not_registered",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="user",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="donor",
            name="weight",
            field=models.DecimalField(decimal_places=0, max_digits=999),
        ),
    ]
