# Generated by Django 5.0.7 on 2024-11-15 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood", "0002_alter_donor_registration_status_alter_donor_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="donation_count",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
