# Generated by Django 5.0.7 on 2024-11-16 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood", "0004_alter_donor_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="registration_status",
        ),
    ]
