# Generated by Django 5.0.7 on 2024-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood", "0006_alter_donor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="gender",
            field=models.CharField(
                choices=[("Nam", "Nam"), ("Nữ", "Nữ")], max_length=5
            ),
        ),
    ]
