# Generated by Django 5.0.7 on 2024-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=15, verbose_name="Contact Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="Blood Type",
                    ),
                ),
                (
                    "required_quantity",
                    models.PositiveIntegerField(verbose_name="Required Quantity (ml)"),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Urgent", "Urgent"),
                            ("Critical", "Critical"),
                        ],
                        max_length=10,
                        verbose_name="Urgency Level",
                    ),
                ),
                (
                    "medical_condition",
                    models.TextField(
                        blank=True, null=True, verbose_name="Medical Condition"
                    ),
                ),
                (
                    "request_date",
                    models.DateField(auto_now_add=True, verbose_name="Request Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Denied", "Denied"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=10,
                        verbose_name="Request Status",
                    ),
                ),
                (
                    "allocated_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Allocated Quantity (ml)"
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Allocation Date"
                    ),
                ),
                (
                    "assigned_hospital",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Assigned Hospital",
                    ),
                ),
                (
                    "doctor_in_charge",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Doctor In Charge",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
        ),
    ]
