# Generated by Django 5.0.7 on 2024-11-20 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("help_blood", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bloodrecipient",
            options={
                "verbose_name": "Người Nhận Máu",
                "verbose_name_plural": "Người Nhận Máu",
            },
        ),
    ]
