# Generated by Django 5.0.7 on 2024-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="Blood Type",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity (ml)")),
                ("donation_date", models.DateField(verbose_name="Donation Date")),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Expired", "Expired"),
                            ("Contaminated", "Contaminated"),
                        ],
                        max_length=15,
                        verbose_name="Quality Status",
                    ),
                ),
                (
                    "storage_unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Storage Unit",
                    ),
                ),
                (
                    "storage_condition",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Storage Condition",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Source of Blood",
                    ),
                ),
                (
                    "blood_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Blood Used (ml)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Used", "Used"),
                            ("Disposed", "Disposed"),
                        ],
                        default="In Stock",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
