# Generated by Django 5.0.7 on 2024-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_blood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodbank",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
    ]
