# Generated by Django 5.0.7 on 2024-11-20 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_blood", "0002_bloodbank_is_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodbank",
            name="is_hidden",
        ),
    ]
