# Generated by Django 5.0.7 on 2024-11-16 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blood", "0004_alter_donor_user"),
        ("event_blood", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blood.donor"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_blood.blooddonationevent",
                    ),
                ),
            ],
            options={
                "unique_together": {("donor", "event")},
            },
        ),
    ]
