# Generated by Django 5.0.7 on 2024-11-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration_blood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donorregistration",
            name="blood_donated",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The amount of blood donated by the donor (in units).",
            ),
        ),
    ]
