# Generated by Django 5.0.7 on 2024-11-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood", "0004_alter_donor_user"),
        ("event_blood", "0001_initial"),
        ("registration_blood", "0002_donorregistration_blood_donated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorregistration",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donors",
                to="blood.donor",
            ),
        ),
        migrations.AlterField(
            model_name="donorregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="event_blood.blooddonationevent",
            ),
        ),
    ]
